services:
  insight:
    image: cybadmin/eveinsight:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./scripts/Docker/Dockerfile
    restart: always
    environment:
      DB_DRIVER: "sqlite3"
      SQLITE_DB_PATH: "Database.db"
      HEADERS_FROM_EMAIL: "YourEmailHere"
      DISCORD_TOKEN: ""
      CCP_CLIENT_ID: ""
      CCP_SECRET_KEY: ""
      CCP_CALLBACK_URL: "https://raw.githubusercontent.com/EVEInsight/Insight/master/Insight/callback/index.html"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_PASSWORD: "pass"
      REDIS_PURGE: "FALSE"
      REDIS_SSL: "FALSE"
      ZK_REDISQ_URL: "https://zkillredisq.stream/listen.php"
      INSIGHT_ADMINS: ""
      #INSIGHT_ENCRYPTION_KEY: ""
      WEBSERVER_ENABLED: "FALSE"
    volumes:
      - insight-data:/app
    networks:
      - insight-net
  redis:
    image: redis:6
    restart: always
    networks:
      - insight-net
    command: --requirepass "pass"
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eveinsight
      POSTGRES_PASSWORD:
      POSTGRES_DB: eveinsight
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - insight-net
networks:
  insight-net:
    driver: bridge
volumes:
  insight-data:
  db_data: